//  copyright lexilogos.com
var car;
function transcrire() {
car = document.conversion.saisie.value;
car = car.replace(/==a/g, "ً");
car = car.replace(/==i/g, "ٍ");
car = car.replace(/==u/g, "ٌ");
car = car.replace(/=a/g, "َ");
car = car.replace(/=i/g, "ِ");
car = car.replace(/=u/g, "ُ");
car = car.replace(/=w/g, "ّ");
car = car.replace(/=o/g, "ْ");

car = car.replace(/’/g, "\'");
car = car.replace(/[aâàā]/g, "ا");
car = car.replace(/اا/g, "آ");
car = car.replace(/b/g, "ب");
car = car.replace(/ب'/g, "پ");
car = car.replace(/p/g, "پ");
car = car.replace(/پ'/g, "ب");
car = car.replace(/t/g, "ت");
car = car.replace(/ت'/g, "ث");
car = car.replace(/ث'/g, "ت");
car = car.replace(/ṯ/g, "ث");
car = car.replace(/[jǧ]/g, "ج");
car = car.replace(/ج'/g, "چ");
car = car.replace(/c/g, "چ");
car = car.replace(/چ'/g, "ح");
car = car.replace(/[HḥḤ]/g, "ح");
car = car.replace(/ح'/g, "خ");
car = car.replace(/[xẖK]/g, "خ");
car = car.replace(/خ'/g, "ج");
car = car.replace(/d/g, "د");
car = car.replace(/د'/g, "ذ");
car = car.replace(/ذ'/g, "ڎ");
car = car.replace(/ڎ'/g, "ڊ");
car = car.replace(/ڊ'/g, "د");
car = car.replace(/r/g, "ر");
car = car.replace(/ر'/g, "ز");
car = car.replace(/ز'/g, "ر");
car = car.replace(/z/g, "ز");
car = car.replace(/s/g, "س");
car = car.replace(/س'/g, "ش");
car = car.replace(/ش'/g, "س");
car = car.replace(/š/g, "ش");
car = car.replace(/[Sṣ]/g, "ص");
car = car.replace(/ص'/g, "ض");
car = car.replace(/ض'/g, "ص");
car = car.replace(/[Dḍ]/g, "ض");
car = car.replace(/[Tṭ]/g, "ط");
car = car.replace(/ط'/g, "ظ");
car = car.replace(/ظ'/g, "ڟ");
car = car.replace(/ڟ'/g,"ط");
car = car.replace(/[Zẓ]/g, "ظ");
car = car.replace(/[gʿ]/g, "ع");
car = car.replace(/ع'/g, "غ");
car = car.replace(/غ'/g, "ڠ");
car = car.replace(/ڠ'/g, "ع");
car = car.replace(/ġ/g, "غ");
car = car.replace(/f/g, "ف");
car = car.replace(/ف'/g, "ڤ");
car = car.replace(/ڤ'/g, "ف");
car = car.replace(/v/g, "ڢ");
car = car.replace(/q/g, "ق");
car = car.replace(/ق'/g, "ڨ");
car = car.replace(/ڨ'/g, "ق");
car = car.replace(/k/g, "ك");
car = car.replace(/ك'/g, "ڮ");
car = car.replace(/ڮ'/g, "ڭ");
car = car.replace(/ڭ'/g, "ࢴ");
car = car.replace(/ࢴ'/g, "ڬ");
car = car.replace(/ڬ'/g, "ك");
car = car.replace(/l/g, "ل");
car = car.replace(/m/g, "م");
car = car.replace(/n/g, "ن");
car = car.replace(/ن'/g, "ڽ");
car = car.replace(/ڽ'/g, "ن");
car = car.replace(/h/g, "ه");
car = car.replace(/ه'/g, "ة");
car = car.replace(/ة'/g, "ه");
car = car.replace(/[wouôûōū]/g, "و");
car = car.replace(/[YIE]/g, "ي");
car = car.replace(/[yieîī]/g, "ى");
car = car.replace(/ى'/g,"ي");
car = car.replace(/ي'/g,"ۑ");
car = car.replace(/ۑ'/g, "ى");
car = car.replace(/-/g, "ء");
car = car.replace(/ʾ/g, "ء");
car = car.replace(/وءء/g, "ؤ");
car = car.replace(/يءء/g, "ئ");
car = car.replace(/اءء/g, "إ");
car = car.replace(/I/g, "إ");
car = car.replace(/A/g, "إ");
car = car.replace(/ءا/g, "أ");
car = car.replace(/_/g, "ـ");
car = car.replace(/\?/g, "؟");
car = car.replace(/\;/g, "؛");
car = car.replace(/\,/g, "،");

startPos = document.conversion.saisie.selectionStart;
endPos = document.conversion.saisie.selectionEnd;

beforeLen = document.conversion.saisie.value.length;
afterLen = car.length;
adjustment = afterLen - beforeLen;

document.conversion.saisie.value = car;

document.conversion.saisie.selectionStart = startPos + adjustment;
document.conversion.saisie.selectionEnd = endPos + adjustment;

var obj = document.conversion.saisie;
obj.focus();
obj.scrollTop = obj.scrollHeight;
}
